// <auto-generated />
namespace EbookApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dodanie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanie));
        
        string IMigrationMetadata.Id
        {
            get { return "202203152142304_dodanie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
